apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.helm_service_39a889c5e9fe59318f48f8b65873e073.name   }}
spec:
  type: {{ .Values.helm_service_39a889c5e9fe59318f48f8b65873e073.type }}
  ports:
    - port: {{ .Values.helm_service_39a889c5e9fe59318f48f8b65873e073.port }}
      targetPort: {{ .Values.helm_service_39a889c5e9fe59318f48f8b65873e073.target_port }}
      protocol: {{.Values.helm_service_39a889c5e9fe59318f48f8b65873e073.protocol}}
  {{- with .Values.helm_service_39a889c5e9fe59318f48f8b65873e073.selector_labels }}
  selector:
      {{- toYaml . | nindent 8 }}
  {{- end }}